@extends('layouts.app')

@section('title', 'Analytics - LESCO EMS')

@push('styles')
<style>
    .tab-container { display: flex; gap: 10px; justify-content: center; margin-bottom: 20px; }
    .tab-btn { padding: 10px 30px; border: 1px solid #ddd; background: #f9f9f9; cursor: pointer; border-radius: 5px; font-weight: bold; color: #666; transition: 0.3s; }
    .tab-btn.active { background: #fff; color: #006633; border: 1px solid #006633; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .chart-box { height: 300px; position: relative; }
    .bottom-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 20px; }
</style>
@endpush

@section('content')
<header class="header">
    <div>
        <h1>Defaulters Analytics Dashboard</h1>
        <p>Live graphical breakdown generated by system data.</p>
    </div>
    <div>
        <strong style="font-size: 24px; color: var(--primary);">{{ number_format($totalDefaulters) }}</strong>
        <span style="color: var(--muted); display: block; font-size: 11px;">Total Defaulters</span>
    </div>
</header>

<div class="card" style="margin-bottom: 20px;">
    <div class="card-header"><h3>DEFAULTERS BY CIRCLE</h3></div>
    <div class="chart-box">
        <canvas id="circleBarChart"></canvas>
    </div>
</div>

<div class="bottom-grid">
    <div class="card">
        <div class="tab-container">
            <button onclick="showChart('tariff', this)" class="tab-btn active">Tariff</button>
            <button onclick="showChart('status', this)" class="tab-btn">Status</button>
            <button onclick="showChart('type', this)" class="tab-btn">Type</button>
        </div>

        <div class="card-header"><h3 id="chart-title">DEFAULTERS BY TARIFF</h3></div>
        <div class="chart-box" style="height: 220px;"> <canvas id="mainDonutChart"></canvas>
        </div>
    </div>

    <div class="card" style="background: var(--primary); color: white;">
        <h3 style="border-bottom: 1px solid rgba(255,255,255,0.2); padding-bottom: 10px; margin-top:0;">Financial Summary</h3>
        <div style="margin-top: 20px;">
            <p style="font-size: 12px; margin: 0 0 5px; opacity: 0.8;">Total Outstanding</p>
            <h2 style="margin: 0 0 20px; font-size: 28px;">Rs {{ number_format($totalOutstanding, 2) }}</h2>

            <p style="font-size: 12px; margin: 0 0 5px; opacity: 0.8;">Average Default Amount</p>
            <h2 style="margin: 0; font-size: 22px;">Rs {{ number_format($avgOutstanding ?? 0, 2) }}</h2>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    const chartData = {
        tariff: { title: 'DEFAULTERS BY TARIFF', labels: {!! $byTariff->pluck('tariff_type')->toJson() !!}, data: {!! $byTariff->pluck('count')->toJson() !!}, colors: ['#2ecc71', '#f1c40f', '#3498db', '#9b59b6', '#e74c3c'] },
        status: { title: 'DEFAULTERS BY STATUS', labels: {!! $byStatus->pluck('status')->toJson() !!}, data: {!! $byStatus->pluck('count')->toJson() !!}, colors: ['#e74c3c', '#2ecc71'] },
        type:   { title: 'DEFAULTERS BY TYPE', labels: {!! $byType->pluck('consumer_type')->toJson() !!}, data: {!! $byType->pluck('count')->toJson() !!}, colors: ['#2ecc71', '#3498db'] }
    };

    let activeChart;
    function showChart(type, btn) {
        document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        document.getElementById('chart-title').innerText = chartData[type].title;
        if (activeChart) activeChart.destroy();
        activeChart = new Chart(document.getElementById('mainDonutChart').getContext('2d'), {
            type: 'doughnut',
            data: { labels: chartData[type].labels, datasets: [{ data: chartData[type].data, backgroundColor: chartData[type].colors }] },
            options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'right' } } }
        });
    }

    // Initialize Top Circle Bar Chart (Set maintainAspectRatio to false so it respects chart-box constraints)
    new Chart(document.getElementById('circleBarChart').getContext('2d'), {
        type: 'bar',
        data: {
            labels: {!! $byCircle->pluck('circle')->toJson() !!},
            datasets: [{ label: 'Defaulters', data: {!! $byCircle->pluck('count')->toJson() !!}, backgroundColor: '#2ecc71', borderRadius: 3 }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: { legend: { display: false } }
        }
    });

    window.onload = () => showChart('tariff', document.querySelector('.tab-btn'));
</script>
@endpush
